// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_bkZfIexdGfmDXbZQ3SXJtvUFpjZpgi4',
    appId: '1:1097268000307:web:c37516b910396f27d89546',
    messagingSenderId: '1097268000307',
    projectId: 'practice-15d07',
    authDomain: 'practice-15d07.firebaseapp.com',
    databaseURL: 'https://practice-15d07-default-rtdb.firebaseio.com',
    storageBucket: 'practice-15d07.firebasestorage.app',
    measurementId: 'G-2NJDK1PJ73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNSeXMT7nEubANqY-dEtzaocrebbmC7y0',
    appId: '1:1097268000307:android:0b1c36257cad2407d89546',
    messagingSenderId: '1097268000307',
    projectId: 'practice-15d07',
    databaseURL: 'https://practice-15d07-default-rtdb.firebaseio.com',
    storageBucket: 'practice-15d07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQwK7eCWHvt8yGwK8sOrBbEdrvvI1Jy2s',
    appId: '1:1097268000307:ios:fb880475a380c423d89546',
    messagingSenderId: '1097268000307',
    projectId: 'practice-15d07',
    databaseURL: 'https://practice-15d07-default-rtdb.firebaseio.com',
    storageBucket: 'practice-15d07.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQwK7eCWHvt8yGwK8sOrBbEdrvvI1Jy2s',
    appId: '1:1097268000307:ios:fb880475a380c423d89546',
    messagingSenderId: '1097268000307',
    projectId: 'practice-15d07',
    databaseURL: 'https://practice-15d07-default-rtdb.firebaseio.com',
    storageBucket: 'practice-15d07.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_bkZfIexdGfmDXbZQ3SXJtvUFpjZpgi4',
    appId: '1:1097268000307:web:22d8584596cf0086d89546',
    messagingSenderId: '1097268000307',
    projectId: 'practice-15d07',
    authDomain: 'practice-15d07.firebaseapp.com',
    databaseURL: 'https://practice-15d07-default-rtdb.firebaseio.com',
    storageBucket: 'practice-15d07.firebasestorage.app',
    measurementId: 'G-MQ3NYL7QTL',
  );
}
